#:schema node_modules/wrangler/config-schema.json
name = "good-boyfriend"
main = "src/index.js"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#workers-ai
[ai]
binding = "AI"

[[kv_namespaces]]
binding = "GIRLFRIEND_LOCATION"
id = "61ac06c4b11a42c3acdbcacdebd986ce"

[vars]
MODEL_ID = "@cf/meta/llama-3.1-8b-instruct"
PROMPT_INSTRUCTIONS = "Write a sweet good morning message for my girlfriend that also gives her a weather update (including helpful things like wearing a raincoat if it's raining, or staying shady if it's hot). Do not include any foreword, just give me the message directly. Do not make it overly romantic, keep it light and fun. Keep it to around 5 sentences. Use one or two emojis to make it fun! Do not make any plans or promise anything in the message. Don't include quotation marks."