#:schema node_modules/wrangler/config-schema.json
name = "good-boyfriend"
main = "src/index.js"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#workers-ai
[ai]
binding = "AI"

[[kv_namespaces]]
binding = "GIRLFRIEND_LOCATION"
id = "61ac06c4b11a42c3acdbcacdebd986ce"